# Generated by Django 6.0.3 on 2026-04-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.material')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_usados', to='gestao.servico')),
            ],
        ),
    ]
